### ISSUE TITLE
Meta: Goal Setting

### ISSUE THREAD

**Issue by DonaldTsang** [DangerOnTheRanger/maniwani#110]
As a measure of user activity, it should be compared with
- https://endchan.xyz
- https://waifuist.pro
- https://bbw-chan.nl

**Comment by DangerOnTheRanger** [comment]
This isn't really a concern of mine. Maniwani in my eyes is a fun hobby project that just happens to have Futatsu and other deployments as a nice side effect; how popular any of them are/how popular Maniwani itself is doesn't matter to me, and I'll keep working on it no matter how popular it is as long as I have fun doing so, so I'm closing this with wontfix.

**Comment by samip5** [comment]
If I were to implement something like this, would you be open for a PR? @DangerOnTheRanger

**Comment by DonaldTsang** [comment]
@samip5 I would like to invite you to something else that can give you perspective on what should be included in an imageboard

**Comment by samip5** [comment]
@DonaldTsang Python related or what?

**Comment by DonaldTsang** [comment]
@samip5 features in general, regarding imageboards of all sorts from PHP based to JS based.
https://github.com/fatchan/jschan/issues/2 https://github.com/fatchan/jschan/issues/39 https://github.com/fatchan/jschan/issues/40 https://github.com/fatchan/jschan/issues/55 https://github.com/fatchan/jschan/issues/57

**Comment by samip5** [comment]
Hmm, I kinda see what you mean, but this is a hobby project as I have understood.

**Comment by DonaldTsang** [comment]
The problem is that there is no Python based imageboard in the market that is feature reach other than https://github.com/Floens/uchan (but that is old now)

**Comment by samip5** [comment]
I can see what you mean, I choose to look into this purely due to the fact that I know my way around Flask and Python which there are not many imageboard software for.

**Comment by DangerOnTheRanger** [comment]
Maniwani is still just a hobby project to me - so I'm not really concerned with how popular it is in the grand scheme of things. I'll support anyone running a Maniwani instance to the best of my ability, and I'll take feature requests that I think worth spending my own time on/accept PRs that I think are good for the project overall, but I'm not really treating it as an outright competitor to other imageboard engines, if that makes sense.
