### ISSUE TITLE
Unable to run docker-compose stack

### ISSUE THREAD

**Issue by samip5** [DangerOnTheRanger/maniwani#124]
I'm unable to do get it running by using these commands:
```
docker-compose build
docker-compose run captchouli bootstrap
docker-compose up -d
docker-compose run maniwani bootstrap
```
Tat first bootsrap fails, if the stack is not online yet and when I do get it to bootsrap, it won't start the actual container correctly.

Docker version 19.03.4-ce, build 9013bf583a
Docker-compose version 1.24.1, build unknown
Running on Manjaro.

Log/traceback from maniwani container:
```
DAMN ! worker 1 (pid: 865) died :( trying respawn ...
worker respawning too fast !!! i have to sleep a bit (2 seconds)...
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gevent/__init__.py", line 87, in <module>
    from gevent._hub_local import get_hub
  File "/usr/local/lib/python3.6/site-packages/gevent/_hub_local.py", line 101, in <module>
    import_c_accel(globals(), 'gevent.__hub_local')
  File "/usr/local/lib/python3.6/site-packages/gevent/_util.py", line 105, in import_c_accel
    mod = importlib.import_module(cname)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'gevent.__hub_local'
```
docker exec -it maniwani_maniwani_1 sh:
```
/maniwani $ pip install gevent
Requirement already satisfied: gevent in /usr/local/lib/python3.6/site-packages (1.4.0)
Requirement already satisfied: greenlet>=0.4.14; platform_python_implementation == "CPython" in /usr/local/lib/python3.6/site-packages (from gevent) (0.4.15)
```
And the nginx container says Gateway Time-Out due to that.

**Comment by DangerOnTheRanger** [comment]
Odd, I have Docker 18.09.1 (build 4c52b90) and docker-compose 1.21.2  (build a133471) on Debian Sid and I can build and bootstrap just fine off of the master branch. What does the captchouli bootstrap give as an error message, out of curiosity?

As far as the `gevent` error goes, I did some looking around and it seems to be related to one of the following:
* [no module named gevent even though it is installed](https://stackoverflow.com/questions/49198346/no-module-named-gevent-even-though-it-is-installed)
* [Docker-->ModuleNotFoundError: No module named 'gevent' ](https://github.com/apache/incubator-superset/issues/7522)

Can you try installing `gevent` using the Alpine package manager and see what happens?

**Comment by samip5** [comment]
> Odd, I have Docker 18.09.1 (build 4c52b90) and docker-compose 1.21.2 (build a133471) on Debian Sid and I can build and bootstrap just fine off of the master branch. What does the captchouli bootstrap give as an error message, out of curiosity?
> 
> As far as the `gevent` error goes, I did some looking around and it seems to be related to one of the following:
> 
> * [no module named gevent even though it is installed](https://stackoverflow.com/questions/49198346/no-module-named-gevent-even-though-it-is-installed)
> * [Docker-->ModuleNotFoundError: No module named 'gevent' ](https://github.com/apache/incubator-superset/issues/7522)
> 
> Can you try installing `gevent` using the Alpine package manager and see what happens?

Oh, it didin't show anything that it had to wait for 20 fetch times for it to complete, never mind on that.

I added uwsgi-gevent to the Dockerfile for maniwani, but still do dice. Same error.

**Comment by DangerOnTheRanger** [comment]
By `gevent` I was referring to [py3-gevent](https://pkgs.alpinelinux.org/package/edge/community/x86/py3-gevent), sorry - did you try to install that package via `apk`?

**Comment by samip5** [comment]
After I added that, I got somewhere.

Logs from maniwani:
```
sh: devmode: unknown operand
sh: bootstrap: unknown operand
sh: update: unknown operand
[uWSGI] getting INI configuration from ./deploy-configs/uwsgi.ini
open("/usr/lib/uwsgi/gevent3_plugin.so"): No such file or directory [core/utils.c line 3724]
!!! UNABLE to load uWSGI plugin: Error loading shared library /usr/lib/uwsgi/gevent3_plugin.so: No such file or directory !!!
*** Starting uWSGI 2.0.18 (64bit) on [Sun Dec  8 21:40:18 2019] ***
compiled with version: 8.3.0 on 13 November 2019 22:04:37
os: Linux-5.3.12-1-MANJARO #1 SMP PREEMPT Thu Nov 21 10:55:53 UTC 2019
nodename: b2e8068e4bab
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 16
current working directory: /maniwani
detected binary path: /usr/sbin/uwsgi
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:3031 fd 3
Python version: 3.7.5 (default, Oct 17 2019, 12:25:15)  [GCC 8.3.0]
Python main interpreter initialized at 0x56330a3e5340
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 364600 bytes (356 KB) for 4 cores
*** Operational MODE: preforking ***
ModuleNotFoundError: No module named 'wsgi'
unable to load app 0 (mountpoint='') (callable not found or import error)
Traceback (most recent call last):
  File "app.py", line 1, in <module>
    import gevent.monkey
  File "/usr/local/lib/python3.6/site-packages/gevent/__init__.py", line 87, in <module>
    from gevent._hub_local import get_hub
  File "/usr/local/lib/python3.6/site-packages/gevent/_hub_local.py", line 101, in <module>
    import_c_accel(globals(), 'gevent.__hub_local')
  File "/usr/local/lib/python3.6/site-packages/gevent/_util.py", line 105, in import_c_accel
    mod = importlib.import_module(cname)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'gevent.__hub_local'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 6)
spawned uWSGI worker 1 (pid: 7, cores: 1)
spawned uWSGI worker 2 (pid: 8, cores: 1)
spawned uWSGI worker 3 (pid: 9, cores: 1)
spawned uWSGI worker 4 (pid: 10, cores: 1)
--- no python application found, check your startup logs for errors ---
[pid: 10|app: -1|req: -1/1] 172.22.0.1 () {46 vars in 770 bytes} [Sun Dec  8 21:41:11 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 8|app: -1|req: -1/2] 172.22.0.1 () {44 vars in 697 bytes} [Sun Dec  8 21:41:11 2019] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
```

**Comment by DangerOnTheRanger** [comment]
So it looks like uWSGI is booting up okay now, but gevent still has problems.

```
!!! UNABLE to load uWSGI plugin: Error loading shared library /usr/lib/uwsgi/gevent3_plugin.so: No such file or directory !!!
```

This strikes me as odd - can you ensure that `gevent3_plugin.so` exists in `/usr/lib/uwsgi`? If you can't find it, try looking in other library directories if possible. Do you still have `uwsgi-gevent3` installed? If you're not on Alpine edge - the Maniwani Dockerfile defaults not to edge, but to 3.10 - you'll need to explicitly install `uwsgi-gevent3` and not `uwsgi-gevent`.

**Comment by samip5** [comment]
> So it looks like uWSGI is booting up okay now, but gevent still has problems.
> 
> ```
> !!! UNABLE to load uWSGI plugin: Error loading shared library /usr/lib/uwsgi/gevent3_plugin.so: No such file or directory !!!
> ```
> 
> This strikes me as odd - can you ensure that `gevent3_plugin.so` exists in `/usr/lib/uwsgi`? If you can't find it, try looking in other library directories if possible. Do you still have `uwsgi-gevent3` installed? If you're not on Alpine edge - the Maniwani Dockerfile defaults not to edge, but to 3.10 - you'll need to explicitly install `uwsgi-gevent3` and not `uwsgi-gevent`.
> 
> EDIT: Looking back over your log, I notice you have Python 3.7 and not 3.6 (and a slightly newer version of uWSGI) - did you modify the `FROM python:3.6-alpine AS dev` line in the Dockerfile?

No, I did not modify it.
My Manjaro install does have newer Python.

I'm currently building it again from the non-modified Dockerfile in the repo to see if that fixes anything.

Update: Yes, it did not change anything, and I don't know where it get's that Python 3.7, but I do have that installed on the host.

**Comment by DangerOnTheRanger** [comment]
If you open a shell inside the container and run something like `python3 --version`, what does that output? I don't see how the container would be picking up your system installation of Python, but I want to make sure the container itself has 3.6.

Also, are you sure that your Manjaro installation has 3.7.4? The log you posted reported Python 3.7.5, so I just wanted to check.

**Comment by samip5** [comment]
Running `python3 --version` in host:
```
Python 3.7.4
```

Running inside maniwani:
```
docker exec -it maniwani_maniwani_1 sh
/maniwani $ python3 --version
Python 3.6.9
```

UWSGI logs still show Python 3.7.5 and I don't know how.

**Comment by DangerOnTheRanger** [comment]
Could be that uWSGI somehow has a different version of Python 3 it's using. What does `uwsgi --plugin python3 -s :0` output if you run it in a shell in the container? I notice also your logs are reporting uWSGI `2.0.18`, whereas mine reports `2.0.17`, though I wouldn't think a patch-level version mismatch would make a difference.

**Comment by samip5** [comment]
That command outputs Python version as 3.7.5.

```
/maniwani $ uwsgi --plugin python3 -s :0
*** Starting uWSGI 2.0.18 (64bit) on [Sun Dec  8 23:19:33 2019] ***
compiled with version: 8.3.0 on 13 November 2019 22:04:37
os: Linux-5.3.12-1-MANJARO #1 SMP PREEMPT Thu Nov 21 10:55:53 UTC 2019
nodename: a33333631da6
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 16
current working directory: /maniwani
detected binary path: /usr/sbin/uwsgi
*** WARNING: you are running uWSGI without its master process manager ***
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :35677 (port auto-assigned) fd 3
Python version: 3.7.5 (default, Oct 17 2019, 12:25:15)  [GCC 8.3.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x56369e755d80
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72920 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 511, cores: 1)
```

**Comment by DangerOnTheRanger** [comment]
From that output and from experimenting with my own system, the uWSGI Python plugin has a version independent of the system Python inside the container, which makes sense in retrospect. Can you try installing uWSGI 2.0.17 by modifying the Dockerfile's installation of uWSGI to read:
```
RUN apk add uwsgi-python3=2.0.17 uwsgi-gevent3=2.0.17 uwsgi-gevent=2.0.17 py3-gevent uwsgi-http=2.0.17
```

**Comment by samip5** [comment]
> From that output and from experimenting with my own system, the uWSGI Python plugin has a version independent of the system Python inside the container, which makes sense in retrospect. Can you try installing uWSGI 2.0.17 by modifying the Dockerfile's installation of uWSGI to read:
> 
> ```
> RUN apk add uwsgi-python3=2.0.17 uwsgi-gevent3=2.0.17 uwsgi-gevent=2.0.17 py3-gevent uwsgi-http=2.0.17
> ```

It fails to build.
```
Step 3/45 : RUN apk add uwsgi-python3=2.0.17 uwsgi-gevent3=2.0.17 uwsgi-gevent=2.0.17 py3-gevent uwsgi-http=2.0.17
 ---> Running in e9d15124bc91
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  uwsgi-gevent-2.0.18-r1:
    breaks: world[uwsgi-gevent=2.0.17]
  uwsgi-gevent3-2.0.18-r1:
    breaks: world[uwsgi-gevent3=2.0.17]
  uwsgi-http-2.0.18-r1:
    breaks: world[uwsgi-http=2.0.17]
  uwsgi-python3-2.0.18-r1:
    breaks: world[uwsgi-python3=2.0.17]
ERROR: Service 'maniwani' failed to build: The command '/bin/sh -c apk add uwsgi-python3=2.0.17 uwsgi-gevent3=2.0.17 uwsgi-gevent=2.0.17 py3-gevent uwsgi-http=2.0.17' returned a non-zero code: 4
```

**Comment by DangerOnTheRanger** [comment]
Sorry, can you remove the old line that read:
```
RUN apk add uwsgi-python3 uwsgi-gevent3 uwsgi-gevent py3-gevent uwsgi-http
```

**Comment by samip5** [comment]
The Dockerfile where this fails:
```
FROM python:3.6-alpine AS dev
WORKDIR /maniwani
# uwsgi and associated plugins
RUN apk add uwsgi-python3=2.0.17 uwsgi-gevent3=2.0.17 uwsgi-gevent=2.0.17 py3-gevent uwsgi-http=2.0.17
# backend dependencies
RUN pip install pipenv
# dependencies for Pillow
RUN apk add build-base jpeg-dev zlib-dev libwebp-dev
# dependencies for psycopg2
RUN apk add libpq postgresql-dev gcc python3-dev musl-dev
RUN apk add ffmpeg
# frontend dependencies
RUN apk add nodejs nodejs-npm
# workaround for some pip issues on alpine
ENV LIBRARY_PATH=/lib:/usr/lib
COPY Pipfile /maniwani
COPY Pipfile.lock /maniwani
RUN pipenv install --system --deploy
# remove backend build-time dependencies
RUN apk del build-base gcc python3-dev musl-dev jpeg-dev zlib-dev
# point MANIWANI_CFG to the devmode config file
ENV MANIWANI_CFG=./deploy-configs/devmode.cfg
# workaround for uwsgi inexplicably not picking up /usr/local/lib even though
# system python has it
ENV PYTHONPATH=$PYTHONPATH:/usr/local/lib/python3.6/site-packages
# build static frontend files
COPY package.json /maniwani
COPY package-lock.json /maniwani
RUN npm install
COPY Gulpfile.js /maniwani
COPY scss /maniwani/scss
RUN npm run gulp
# remove frontend build-time dependencies
RUN apk del nodejs-npm nodejs
RUN rm -rf node_modules
# copy source files over
COPY migrations /maniwani/migrations
COPY *.py /maniwani/
COPY blueprints /maniwani/blueprints
COPY build-helpers /maniwani/build-helpers
COPY deploy-configs /maniwani/deploy-configs
COPY model /maniwani/model
COPY resources /maniwani/resources
COPY templates /maniwani/templates
COPY ./build-helpers/docker-entrypoint.sh ./docker-entrypoint.sh
# bootstrap dev image
RUN python bootstrap.py
EXPOSE 5000

ENTRYPOINT ["sh", "./docker-entrypoint.sh", "devmode"]

FROM dev AS prod
WORKDIR /maniwani
# clean up dev image bootstrapping
RUN rm ./deploy-configs/test.db
RUN rm -r uploads
ENV MANIWANI_CFG=./deploy-configs/maniwani.cfg
# chown and switch users for security purposes
RUN adduser -D maniwani
RUN chown -R maniwani:maniwani ./
USER maniwani

# expose uWSGI
EXPOSE 3031
ENTRYPOINT ["sh", "./docker-entrypoint.sh"]
```

**Comment by DangerOnTheRanger** [comment]
So apparently Alpine [doesn't keep old package versions around](https://medium.com/@stschindler/the-problem-with-docker-and-alpines-package-pinning-18346593e891), at least in the context of a single version of Alpine - unfortunate, but it explains the previous error with `apk`. In that case, I think an upgrade to Python 3.7 is the easiest route, so swap the first line to read:

```
FROM python:3.7-alpine AS dev
```

And then the line that currently reads:

```
ENV PYTHONPATH=$PYTHONPATH:/usr/local/lib/python3.6/site-packages
```

Change it to:

```
ENV PYTHONPATH=$PYTHONPATH:/usr/local/lib/python3.7/site-packages
```

Then try rebuilding. Upgrading Python will likely take more effort than this, but I believe going from 3.6 to 3.7 to probably be the easiest way out at this point. It's not all bad - if Alpine irrevocably upgrading packages is in fact the issue, then that means Maniwani has been broken Docker-wise for a little while now, and we're in the process of fixing it. (I haven't rebuilt my base image from scratch in a long time, which is probably why mine is still fine.)

**Comment by samip5** [comment]
That did the trick, it booted and I can access it now via http://127.0.0.1:5000/ :)
