### ISSUE TITLE
clearing the db

### ISSUE THREAD

**Issue by therealjr** [DangerOnTheRanger/maniwani#148]
I know it has already been specified on how to clear the DB but what is documented doesn't seem to be working for me. Is the test.db file inside of a container? If so, which container? I removed all files labeled test.db from my host but data is still getting loaded. Can anyone help me figure out exactly how to clear the db?

**Comment by DangerOnTheRanger** [comment]
As per [README.md](https://github.com/DangerOnTheRanger/maniwani#with-docker---production-image-and-environment), if you're using `docker-compose` and not using devmode, you'll need to remove the `compose-data` directory to clear the postgres database and the S3 server. Removing the `compose-captchouli` directory removes the download captchouli images.

**Comment by therealjr** [comment]
Thank you very much!
