### ISSUE TITLE
sqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) null value in column "thread" violates not-null constraint

### ISSUE THREAD

**Issue by therealjr** [DangerOnTheRanger/maniwani#149]
https://pastebin.com/dhc5QaEL

I don't know why I'm getting this error. I'm posting to the site using the correct intended API.

**Comment by therealjr** [comment]
The issue seems to stem from purging older threads. The function slide_last_thread within thread.py

**Comment by therealjr** [comment]
I think it has to do with the tags column.

**Comment by therealjr** [comment]
DETAIL:  Failing row contains (1, :::id:::hdqs1d:::locked:::False:::spoiler:::False:::body::::::su..., :::source:::reddit, null, 2020-06-22 11:44:38.015974, 606, 606, null).


I couldn't gather anymore information. I went as far as to print all of the tables out and look at which ones contained Threads and none of them appeared to have null references. So idk what's going on.

**Comment by therealjr** [comment]
The null entry is in table post for column thread. This error exists only for the very first post on the board, the rest seem to have entries in them.

**Comment by therealjr** [comment]
I just tested this on a fresh install with no modifications to the software and I get this error.

**Comment by DangerOnTheRanger** [comment]
Does the error occur upon posting a single thread? If memory serves from our conversation on IRC, this error occurs after several threads have already been posted. Is that still the case? I've been trying to replicate it with no luck so far, so I'm trying to narrow down what the cause could be.

One other thing real quick: I've been making threads in my test at a fairly slow rate (1 thread per 3 seconds) - how often are you trying to post threads?

**Comment by DangerOnTheRanger** [comment]
For the record, the problem was that threads were getting deleted before their posts were, so when a thread got slid off the catalog and deleted, its posts would have their `thread` column update to `NULL`, triggering the not-null constraint. b29745d deletes a thread's posts before the thread itself gets deleted, thus preserving the constraint.
