### ISSUE TITLE
How do I modify db tables for maniwani?

### ISSUE THREAD

**Issue by therealjr** [DangerOnTheRanger/maniwani#154]
I'm trying to write some new features for the software but I cannot seem to access the database. How should I go about modifying the db? (such as adding new tables, etc.)

**Comment by DangerOnTheRanger** [comment]
Maniwani uses Flask-SQLAlchemy and Flask-Migrate, so if you're familiar with using SQLAlchemy as an ORM and Alembic for managing database migrations, things work more or less like what you'd expect. If you're not, the gist of it is:

1. First, create a class that represents a table in your database (see [model/Post.py](https://github.com/DangerOnTheRanger/maniwani/blob/24dc12d13695ac839c17e22e049bd593ba9f6123/model/Post.py#L82), for instance)
2. Then, to integrate your new table with the migration system (allowing pre-existing deployments to use your table), [generate a migration](https://github.com/DangerOnTheRanger/maniwani/blob/05d2164fd8646d808dd4e0d880bc375a4166b87a/CONTRIBUTING.md#generating-a-migration). The migration system also sets up empty tables for the first time for newly-made databases.

For more on how SQLAlchemy works, you might want to check out their [documentation](https://docs.sqlalchemy.org/en/13/). The Flask-SQLAlchemy [quickstart](https://flask-sqlalchemy.palletsprojects.com/en/2.x/quickstart/#a-minimal-application) also has some good info. You probably won't need to interact with Flask-Migrate/Alembic that much unless your migration needs something special (it probably doesn't unless any updated database needs to have the new columns filled in), but you can check out Flask-Migrate's [docs](https://flask-migrate.readthedocs.io/en/latest/#example) just in case.
