### ISSUE TITLE
Database migration support

### ISSUE THREAD

**Issue by DangerOnTheRanger** [DangerOnTheRanger/maniwani#27]
Probably fairly easily done through something like [Flask-Migrate](https://github.com/miguelgrinberg/Flask-Migrate) or something similar, but it still needs to be done. There's not a whole lot of trickery involved with Maniwani's schema, and I see it settling down pretty quickly after the production milestone is hit, but it's still a little silly that we need to wipe the database after every little change as it stands.

**Comment by 9034725985** [comment]
Kind of off-topic but personally, I'm not a big fan of ORM anymore. Maybe I was naive but it seems I have to write SQL or spend more time to not write SQL for anything that isn't straightforward. :(

**Comment by DangerOnTheRanger** [comment]
Complicated queries can get unwieldy in an ORM, I agree - for me, most of the advantages of something like SQLAlchemy stem from being able to get/set attributes as if I were interfacing with any old class without having to worry about the behind-the-scenes stuff outside of the occasional flush/commit, plus not having to worry about some other things like proper escaping.

**Comment by DangerOnTheRanger** [comment]
Fixed as of 5e9f207d411b331ac3bbdb9be49ed7ac308cad1c. The current database migration strategy is to locally run `pipenv run flask db migrate` and maintain the resulting `migrations` folder here in version control, then running `docker-compose run maniwani migrate` or the equivalent in production while having the `migrations` folder mounted in the image.
