### ISSUE TITLE
Brand identity for individual boards

### ISSUE THREAD

**Issue by 9034725985** [DangerOnTheRanger/maniwani#4]
Thank you for accepting my last pull request. 

I was thinking maybe we can include the name of the current board somewhere on the navigation bar? Thoughts?  

https://screenshotscdn.firefoxusercontent.com/images/ab2b0214-8d37-4c9b-a2d9-7c6ca8aea123.png

**Comment by DangerOnTheRanger** [comment]
Yeah, I had been mulling over the problem of how it's not possible to know what board you're on outside of the title. Any suggestions on where to put it? For what it's worth, there's currently support in the base template for putting arbitrary content on the right side of the navbar, as opposed to the left like the normal menu links.

**Comment by DangerOnTheRanger** [comment]
Going to close this for the time being, since the catalog link mentions which board the user is currently browsing.
