### ISSUE TITLE
Unable to run as a non docker instance. //Gulp not found//

### ISSUE THREAD

**Issue by gjdunga** [DangerOnTheRanger/maniwani#49]
I am trying to run this on a virgin ubuntu 18.4 VPS. 
I am a novice, and I'm stuck at gulp as it's not found. 

Suggestions?

**Comment by DangerOnTheRanger** [comment]
Installation of gulp should have been handled by running `npm install` (`ls node_modules | grep gulp` lists `gulp`/`gulp-sass`, correct?) - if not, you should be able to install it with `sudo npm install -g gulp` as long as you already have npm, I think. I'll try to replicate the issue myself with a VM over the coming couple of days if that doesn't seem to fix things, either

**Comment by gjdunga** [comment]
Thank you! "sudo npm install -g gulp" was the correct incantation. 

I get the following warnings:
npm WARN optional Skipping failed optional dependency /gulp/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.7

I'm assuming those are simply "warnings" and are not a requirement of maniwani?

**Comment by DangerOnTheRanger** [comment]
Yes - `fsevents` is only a requirement for Gulp on OSX, those warnings can be safely ignored. I'm a little perplexed that the `sudo npm install -g gulp` was necessary, and I'll still try to look into that matter over the next few days.

**Comment by gjdunga** [comment]
I would most likely consider it 'Pebcac'. I can follow a recipe fairly well, but my goal of putting this up without docker (So I can understand how it works) is helping to push my learning curve.  

The only thing I can say is at first I set up the server with a lamp stack just out of routine, but I had to remove php7.2 because libssl1.0-dev is different between php7.2 and a nodejs-dev dependency with node-gyp. The Ubuntu package for node-gyp apparently statically binds to that version of ssl and does not alter binding.gyp to include the lib's and include files.   
 
Source: https://github.com/nodegit/nodegit/issues/1490#issuecomment-393681634  

*Please Don't ask me how far the rabbit hole I went down to find that... :)

**Comment by DangerOnTheRanger** [comment]
Huh, weird. I'm gonna go ahead and close this issue for the time being - on a side note, I couldn't discern whether or not you have an S3/S3-compatible store set up, but until I/someone else fixes #36 they're currently the only way to serve static files/attachments in Maniwani, so please keep that in mind!
