### ISSUE TITLE
Shrinking over-sized board list

### ISSUE THREAD

**Issue by DonaldTsang** [DangerOnTheRanger/maniwani#58]
The board list should be more compact, maybe double the columns in case there are more boards.
Also a standard board list like how OpenIB does it would be helpful when searching.

**Comment by DangerOnTheRanger** [comment]
I think I get what you're getting at, but if possible do you think you could supply a mockup or an image that basically shows what you want? I want to make sure we're on the same page before moving forward with this.

**Comment by DonaldTsang** [comment]
![image](https://user-images.githubusercontent.com/10583082/54879866-3ba21c80-4e79-11e9-81eb-9527b55e5433.png)
Notice the default is 5 columns, which is too large, try 8~12 columns

**Comment by DangerOnTheRanger** [comment]
I think the relevant CSS is largely located in `templates/board-index.html` if you want to try playing around with the column sizes; it should be a relatively simple matter of adjusting the `.board .board-sizer` selector to shrink it a bit when the screen is sufficiently large.

An alternative that I think would have some merit is to rework the board index to use purely CSS the way the catalog/firehose does now, but that would admittedly take a lot more effort than tweaking a single CSS selector.

**Comment by DonaldTsang** [comment]
If you want to be technical with CSS please use pixel based or em/rem-based, such that it is dynamic across big and small screen (<3 phone posters)

**Comment by DangerOnTheRanger** [comment]
Yeah, I wrote the board index back before I knew things like that; the current catalog implementation scales in the way you're describing. If I get around to it (or someone submits a PR ;) that would be a good thing to fix.

**Comment by DangerOnTheRanger** [comment]
Closing since the board index is now pure CSS as of #159 and should responsively shrink/grow now.
