### ISSUE TITLE
Why do we convert IP address to integer?

### ISSUE THREAD

**Issue by 9034725985** [DangerOnTheRanger/maniwani#6]
I see that we convert IP address to integer. 
```
[2018-08-12 09:57:14,562] ERROR in app: Exception on /thread/new [POST]
... 
def ip_to_int(ip_str):
    # TODO: IPv6 support
    segments = [int(s) for s in ip_str.split(".")]
    segments.reverse()
    ip_num = 0
    for segment in segments:
        ip_num = ip_num | segment
        ip_num = ip_num << 8
    return ip_num
```

When I try to use Postgresql, it doesn't let me use integers outside of (-2,147,483,648, 2,147,483,647) because I get four billion something from my IP address.  

```
 [SQL: 
'INSERT INTO poster 
(hex_string, ip_address, thread, slip) 
VALUES (%(hex_string)s, %(ip_address)s, %(thread)s, %(slip)s) 
RETURNING poster.id'] 
[
  parameters: 
    {'hex_string': 'A412', 'ip_address': 4 xxx xxx xxx, 'thread': 1, 'slip': None}
] 
(Background on this error at: http://sqlalche.me/e/9h9h)
127.0.0.1 - - [12/Aug/2018 09:57:14] "POST /thread/new HTTP/1.1" 500 -
```

**Comment by DangerOnTheRanger** [comment]
Silly premature optimization on my part (comparing two ints is O(1) compared to O(n) string comparison), and probably not something that should've been implemented, honestly. Especially when the intersection of the poster table with the relevant thread ID already brings us down to probably less than 100 rows per query.

Everything should still work if you take out `ip_to_int` and pass the IP directly to the `Poster` constructor + change the column type of `Poster.ip_address` to a string, I think. If you can put that in a PR, that'd be great. Thanks for experimenting with postgres, by the way. Definitely a big step in getting Maniwani production-ready.

**Comment by DangerOnTheRanger** [comment]
Closing since #18 fixes this - thanks again!
