### ISSUE TITLE
ERROR: Service 'captchouli' failed to build

### ISSUE THREAD

**Issue by psytechno604** [DangerOnTheRanger/maniwani#66]
Step 12/17 : RUN go get github.com/bakape/captchouli/cmd/captchouli
 ---> Running in 4b636001938d
# github.com/mattn/go-sqlite3
gcc: fatal error: Killed signal terminated program cc1
compilation terminated.
ERROR: Service 'captchouli' failed to build: The command '/bin/sh -c go get github.com/bakape/captchouli/cmd/captchouli' returned a non-zero code: 2

**Comment by DangerOnTheRanger** [comment]
Very weird, I've never seen that problem before. I did a little searching around and it seems that gcc dying like that is often a [symptom of a lack of memory](https://github.com/numenta/nupic/issues/1803#issuecomment-72925615). Are you building on a VPS, by any chance?

**Comment by psytechno604** [comment]
yes, on a VPS.. thanks, after I freed some memory build is ok

**Comment by therealjr** [comment]
I'm currently experiencing the same issue. Not running on a VPS
