### ISSUE TITLE
js and css links to http://minio:9000 after clean production install

### ISSUE THREAD

**Issue by psytechno604** [DangerOnTheRanger/maniwani#67]
So, I installed maniwani on my VPS, just tested it without reverse proxy (using http://138.68.95.77:5000/) and realized, that js and css are not loaded because all links refer to http://minio:9000 for some reason. Maybe I am missing something?

PS. Is it possible to switch back to Google catpcha? There is no chance for most of my users to solve captchouli ))

PPS. It will be good to have instructions about imageboard administration, didn't find it anywhere... how to customize list of boards, how to delete messages, ban spammers, etc.

**Comment by DangerOnTheRanger** [comment]
Sounds like you're using the stock `deploy-configs/maniwani.cfg` configuration file - this is set up by default such that the `docker-compose.yml` spec in the repository root will work without modification, but it's not intended to work out of the box in a production environment. I've written a guide on deploying Maniwani based upon my experience running Futatsu in [doc/deploying.md](https://github.com/DangerOnTheRanger/maniwani/blob/master/doc/deploying.md) that should answer most of your questions, but here's a brief overview:

* The http://minio:9000 link is referring to the S3 server that the default/demo `docker-compose` setup expects to be running. Unfortunately with #36 not yet fixed you need to have an S3 instance or S3-compatible object store up and running to deploy Maniwani, though with Minio and `docker-compose` you could theoretically host it on the same machine if you don't want to pay for S3 or another VPS. Let me know if this is a problem for you and I'll see what I can do, maybe prioritize that ticket I mentioned earlier.
* reCAPTCHA support is still in the codebase, just not enabled on Futatsu. The document I linked on deploying should give you the info you need to configure Maniwani for reCAPTCHA.
* I'll start work on an administration guide immediately, honestly didn't expect someone else to set up their own instance this soon, but it's a pleasant surprise. Drop me a link when you've set everything up!

**Comment by psytechno604** [comment]
S3 or another VPS is not an option... "though with Minio and docker-compose you could theoretically host it on the same machine" - well, I'll check this out

another workaround, probably, is to host these files via nginx, but we still need a way to replace links (from absolute http://minio:9000/ to something relative)

**Comment by DangerOnTheRanger** [comment]
It seems as of #68 that #36 may be fixed, but I can't confirm it right now - try using the file/folder backend and seeing what happens.

**Comment by psytechno604** [comment]
please add to doc/deploying.md:

RECAPTCHA_THRESHOLD = 0.7 

- this parameter is needed.

Anyway, I am still getting error 500, because:

`[2019-03-26 20:16:04,840] ERROR in app: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./blueprints/threads.py", line 40, in submit
    thread = NewThread().post_impl()
  File "./model/NewThread.py", line 47, in post_impl
    NewPost().post(thread_id=thread.id)
  File "./model/NewPost.py", line 98, in post
    media = storage.save_attachment(uploaded_file)
  File "./model/Media.py", line 31, in save_attachment
    self._write_attachment(attachment_buffer, media_id, file_ext)
  File "./model/Media.py", line 137, in _write_attachment
    open(full_path, "wb").write(attachment_bytes.getvalue())
FileNotFoundError: [Errno 2] No such file or directory: './uploads/1.png'`

something to do with 'uploads' folder? create it? where? and maybe set permissions or so..

**Comment by psytechno604** [comment]
I can create folders manually:

docker exec -t -i c66126ef2e8d mkdir ./uploads
docker exec -t -i c66126ef2e8d mkdir ./uploads/thumbs

after that everything works, but uploads will disappear after container stop. Need to do something with volumes?

maniwani:
        build: .
        volumes:
            - ./uploads:/maniwani/uploads

- this does not work, 'Permission denied' error...

**Comment by DangerOnTheRanger** [comment]
You're right, I hadn't documented `RECAPTCHA_THRESHOLD`; it's simply the lowest allowed return value from reCAPTCHA that Maniwani will allow through.
As far as the problem with volumes goes, try using [volumes](https://docs.docker.com/storage/volumes/) (see also [here](https://docs.docker.com/compose/compose-file/#volumes)) instead of a bind mount. Docker/docker-compose will create/manage the volume for you, so it should get created with the necessary permissions.

**Comment by psytechno604** [comment]
so, you need to add these commands (right before docker-compose up -d) to deployment process:

mkdir uploads && mkdir uploads/thumbs
chmod -R 757 uploads

**Comment by DangerOnTheRanger** [comment]
And this is with `STORAGE_PROVIDER = "FOLDER"` and allows your setup to work, right? If so, I'll add it to the documentation.

**Comment by psytechno604** [comment]
yes, and SERVE_STATIC = True

and I removed unused containers from docker-compose.yml (captchouli, minio)

**Comment by DangerOnTheRanger** [comment]
The need to create directories is now noted in `doc/deploying.md`, so I'll close this for now.
