### ISSUE TITLE
Editing scss files under scss folder do not reflect changes

### ISSUE THREAD

**Issue by worldeditor11** [DangerOnTheRanger/maniwani#70]
However editing the maniwani.css under static folder will. Seems minified? I might be missing a key workflow here.

**Comment by DangerOnTheRanger** [comment]
I believe you'll have to re-run Gulp if you modify any of the SCSS - there's currently nothing in place to automatically watch the `scss` folder for changes, so you have to rebuild the static files yourself after changing them. If you did that and nothing still changed, try restarting the dev server (the `pipenv run flask run` bit); I think it may cache some static files in memory.

**Comment by worldeditor11** [comment]
> there's currently nothing in place to automatically watch the `scss` folder for changes, so you have to rebuild the static files yourself after changing them. 

After spending an hour and a half of googling, experimenting and testing, I finally able to achieve the auto rebuild whenever any of the scss files changed under scss folder.

You can acquire this by adding the following code to Gulpfile.js:

First create the variable:
`var gulp = require('gulp')`

Add the function to watch any changes scss files under scss folder and then perform build if it is so:
`
function watch() 
{
	gulp.watch('./scss/*.scss', exports.build )
}
`

Finally, add the watch function to the list of tasks so that you can run it on console:
`
exports.watch = watch
`

Once you are done, run the command `npm run gulp watch` and it will automatically rebuild the static files everytime a change has been made to scss files. Of course, you still have to manually refresh the browser but I am working on automating that as well.

**Comment by DangerOnTheRanger** [comment]
Cool - do you want to me to add the change or would you like to submit it as a PR?

**Comment by worldeditor11** [comment]
PR most likely since I want to familirise working with GitHub. I also done automating browser refresh everytime theres a change in template or scss files. It needs browsersync but I assume npm will handle it nicely.

**Comment by DangerOnTheRanger** [comment]
Yeah, it shouldn't be too difficult to install browsersync via npm - that said, I'm not experienced enough with browsersync to say how easy it would be to integrate its proxy, though we could always have everyone manually start the proxy if worst came to worst.

**Comment by DangerOnTheRanger** [comment]
Fairly certain this is fixed - I'll reopen if it's proven otherwise.
