### ISSUE TITLE
Special 8chan-specific markup

### ISSUE THREAD

**Issue by DonaldTsang** [DangerOnTheRanger/maniwani#88]
1. Left-pointing arrow turning quotes pink (`< I am so so so stupid`) (a feature in 8chan)
2. Emphasis text that makes the text bold and red (a feature in 8chan)
3. A spoilered or blacked-out text for anime, comics or others
4. LaTeX-like formatting with `$$`
5. Bold, Italic, Strikethrough, Underline, Code, etc.

**Comment by DangerOnTheRanger** [comment]
Duplicate of #116, so I'm closing this issue.
